version: '3.1'

services:
  frontend: 
    image: lister-front:latest
    restart: always
    depends_on:
      - backend
    ports:
      - 30:80
  
  backend:
    image: lister-back:latest
    restart: always
    depends_on:
      - mongo
    ports:
      - 2000:1500

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: admin

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo